name: Continuous Integration
 
on:
  pull_request:
    branches:
      - master
 
jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Commit
        uses: wagoid/commitlint-github-action@v4

  test:
    needs: commitlint
    runs-on: ubuntu-latest
    container: node:latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PORT: 5432
          POSTGRES_USER: developer
          POSTGRES_PASSWORD: password
          POSTGRES_DB: forumapi_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - name: Install PostgreSQL client
        run: |
          apt-get update
          apt-get install --yes postgresql-client
      - name: Query database
        run: psql -h postgres -d forumapi_test -U developer -c 'SELECT 1;'
        env:
          PGPASSWORD: password
      - name: Checkout repository code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm install
      - name: Eslint
        run: npm run lint
      - name: npm migrate and test
        run: npm run migrate:test up && npm run test
        env:
          CI: true
          PGHOST_TEST: postgres
          PGPORT_TEST: 5432
          PGUSER_TEST: developer
          PGPASSWORD_TEST: password
          PGDATABASE_TEST: forumapi_test
          ACCESS_TOKEN_KEY: ${{ secrets.ACCESS_TOKEN_KEY }}
          REFRESH_TOKEN_KEY: ${{ secrets.REFRESH_TOKEN_KEY }}